[project]
name = "asyncio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=25.1.0",
    "asyncpg>=0.31.0",
    "b>=1.0.0",
    "black>=25.12.0",
    "edgedb>=2.2.0",
]
